title: Extend FontLab
description: Extensions, plugins, scripts, templates for the FontLab professional font editor.
baseurl: "/"
url: "http://extend.fontlab.com"
logo: https://res.cloudinary.com/fontlab/image/fetch/f_auto,w_48,c_scale/https://www.fontlab.com/img/icon-fontlab-7.png
#theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
kramdown:
  parse_block_html: true
heading_anchors: true
collections:
  pages:
    output: true
    permalink: /:path/
permalink: pretty

ga_tracking: UA-313999-1
ga_tracking_anonymize_ip: false

search_enabled: true

search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

footer_content: "Site copyright &copy; 2022 <a target='_blank' href='https://www.fontlab.com/'>Fontlab Ltd</a>. Materials are copyright of their respective rights owners. See license details for each material. "