title: Extend FontLab
email: support@domain.com
author: Fontlab Ltd.
description: Extensions, plugins, scripts, templates for the FontLab professional font editor.
baseurl: "/"
url: "https://extend.fontlab.com"
logo: "/res.cloudinary.com/fontlab/image/fetch/f_auto,w_48,c_scale/https://www.fontlab.com/img/icon-fontlab-7.png"

repo: "https://github.com/fontlabcom/extend-fontlab"
github_user: "fontlabcom"
github_repo: "extend-fontlab"
twitter: Fontlab

remote_theme: vsoch/mkdocs-jekyll
color_scheme: "light"
color: "#8c1515" # primary color for header, buttons
logo_width: 34
accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

markdown: kramdown
kramdown:
  parse_block_html: true
heading_anchors: true
collections:
  pages:
    output: true
    permalink: /:path/
permalink: pretty

exclude: [_site, vendor]


ga_tracking: UA-313999-1
ga_tracking_anonymize_ip: false

search_enabled: true

search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

footer_content: "Site copyright &copy; 2022 <a target='_blank' href='https://www.fontlab.com/'>Fontlab Ltd</a>. Materials are copyright of their respective rights owners. See license details for each material. "